// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/auction/v1/event.proto

package auction

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventReserve is emitted on Msg/Reserve
type EventReserve struct {
	// name is the human readable reserved address
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// owner is the bech32 address of the name's owner
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// resolve is the bech32 address the name resolves to
	Resolve string `protobuf:"bytes,3,opt,name=resolve,proto3" json:"resolve,omitempty"`
	// receiver is the receiver address of nft
	Amount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *EventReserve) Reset()         { *m = EventReserve{} }
func (m *EventReserve) String() string { return proto.CompactTextString(m) }
func (*EventReserve) ProtoMessage()    {}
func (*EventReserve) Descriptor() ([]byte, []int) {
	return fileDescriptor_176e7823189b7a68, []int{0}
}
func (m *EventReserve) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReserve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReserve.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReserve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReserve.Merge(m, src)
}
func (m *EventReserve) XXX_Size() int {
	return m.Size()
}
func (m *EventReserve) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReserve.DiscardUnknown(m)
}

var xxx_messageInfo_EventReserve proto.InternalMessageInfo

func (m *EventReserve) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventReserve) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EventReserve) GetResolve() string {
	if m != nil {
		return m.Resolve
	}
	return ""
}

func (m *EventReserve) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*EventReserve)(nil), "cosmos.auction.v1.EventReserve")
}

func init() { proto.RegisterFile("cosmos/auction/v1/event.proto", fileDescriptor_176e7823189b7a68) }

var fileDescriptor_176e7823189b7a68 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x3d, 0x4e, 0xeb, 0x40,
	0x10, 0xb6, 0x5f, 0xf2, 0xf2, 0xf4, 0xfc, 0x5e, 0x13, 0x2b, 0x12, 0x4e, 0x24, 0x9c, 0x88, 0x2a,
	0x42, 0xca, 0xae, 0x1c, 0xc4, 0x01, 0x08, 0x70, 0x01, 0xd3, 0x51, 0x80, 0xfc, 0x33, 0x72, 0x56,
	0x89, 0x77, 0x22, 0xcf, 0xda, 0xc0, 0x2d, 0x38, 0x06, 0xa2, 0xa2, 0xe0, 0x10, 0x29, 0x23, 0x2a,
	0x2a, 0x40, 0x49, 0x41, 0xcb, 0x11, 0x90, 0xed, 0x8d, 0x28, 0x28, 0x68, 0x76, 0x67, 0xbf, 0xef,
	0x9b, 0x4f, 0x33, 0xdf, 0x5a, 0xbb, 0x11, 0x52, 0x8a, 0xc4, 0x83, 0x3c, 0x52, 0x02, 0x25, 0x2f,
	0x3c, 0x0e, 0x05, 0x48, 0xc5, 0x16, 0x19, 0x2a, 0xb4, 0xdb, 0x35, 0xcd, 0x34, 0xcd, 0x0a, 0xaf,
	0xd7, 0xad, 0xa1, 0xcb, 0x4a, 0xc0, 0x35, 0x5f, 0x3d, 0x7a, 0x3b, 0xda, 0x2c, 0xa5, 0xa4, 0x34,
	0x4a, 0x29, 0xd1, 0x44, 0x27, 0xc1, 0x04, 0xeb, 0x86, 0xb2, 0xd2, 0xa8, 0xab, 0xe5, 0x61, 0x40,
	0xc0, 0x0b, 0x2f, 0x04, 0x15, 0x78, 0x3c, 0x42, 0x21, 0x35, 0xdf, 0x0e, 0x52, 0x21, 0x91, 0x57,
	0x67, 0x0d, 0xed, 0x7d, 0x98, 0xd6, 0xff, 0xd3, 0x72, 0x3e, 0x1f, 0x08, 0xb2, 0x02, 0x6c, 0xdb,
	0x6a, 0xca, 0x20, 0x05, 0xc7, 0x1c, 0x98, 0xc3, 0xbf, 0x7e, 0x55, 0xdb, 0xcc, 0xfa, 0x8d, 0x57,
	0x12, 0x32, 0xe7, 0x57, 0x09, 0x4e, 0x9c, 0xa7, 0xc7, 0x51, 0x47, 0xcf, 0x79, 0x14, 0xc7, 0x19,
	0x10, 0x9d, 0xa9, 0x4c, 0xc8, 0xc4, 0xaf, 0x65, 0xf6, 0xd8, 0xfa, 0x93, 0x01, 0xe1, 0xbc, 0x00,
	0xa7, 0xf1, 0x43, 0xc7, 0x56, 0x68, 0x4f, 0xad, 0x56, 0x90, 0x62, 0x2e, 0x95, 0xd3, 0x1c, 0x34,
	0x86, 0xff, 0xc6, 0x5d, 0xa6, 0xf5, 0xe5, 0x32, 0x4c, 0x2f, 0xc3, 0x8e, 0x51, 0xc8, 0xc9, 0xe1,
	0xf2, 0xa5, 0x6f, 0xdc, 0xbf, 0xf6, 0x87, 0x89, 0x50, 0xd3, 0x3c, 0x64, 0x11, 0xa6, 0x3a, 0x36,
	0x7d, 0x8d, 0x28, 0x9e, 0x71, 0x75, 0xb3, 0x00, 0xaa, 0x1a, 0xe8, 0xee, 0xfd, 0x61, 0xdf, 0xf4,
	0xb5, 0xff, 0xe4, 0x62, 0xb9, 0x76, 0xcd, 0xd5, 0xda, 0x35, 0xdf, 0xd6, 0xae, 0x79, 0xbb, 0x71,
	0x8d, 0xd5, 0xc6, 0x35, 0x9e, 0x37, 0xae, 0x71, 0x7e, 0xf2, 0xdd, 0x90, 0xe2, 0xd9, 0x48, 0xe5,
	0x0a, 0x33, 0x11, 0xcc, 0x89, 0x7f, 0x55, 0x65, 0x2e, 0x65, 0x60, 0x22, 0x82, 0x3a, 0xee, 0xeb,
	0xed, 0x8f, 0x87, 0xad, 0x2a, 0xd9, 0x83, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xd5, 0x32,
	0x4b, 0x0a, 0x02, 0x00, 0x00,
}

func (m *EventReserve) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReserve) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReserve) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Resolve) > 0 {
		i -= len(m.Resolve)
		copy(dAtA[i:], m.Resolve)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Resolve)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventReserve) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Resolve)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventReserve) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReserve: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReserve: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resolve", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resolve = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
