name: Blog
on: 
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.16
    - uses: actions/checkout@v2
    - name: Test Build
      run: |
        cd blog/blog && go get ./... && make install
