# Todo: replace with a call to npm run link:check
name: Check Markdown links
on: 
  schedule: 
    - cron: '* */24 * * *'
  pull_request:
    branches:
      - master
      - b9lab-ida-final-content

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'
