# Todo: replace with a call to npm run link:check
name: Check Markdown links
on: 
  schedule: 
    - cron: '* */24 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
