name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read
jobs:
  lint:
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
