name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "**/go.mod"
      - "**/go.sum"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "**/go.mod"
      - "**/go.sum"
  merge_group:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: run linting
        run: |
          make lint
